### ISSUE TITLE
Need the paper

### ISSUE THREAD

**Issue by 67-LQQ** [zhanggengchen/BRVE#1]
I hope this message finds you well. I was going through the project and noticed references to some papers. I'm particularly interested in learning more about them. Could you please provide the links to the papers mentioned in the project documentation or any related material? It would be immensely helpful for my research. Thank you in advance for your assistance!

**Comment by zhanggengchen** [comment]
Our paper is now available in arxiv (https://arxiv.org/abs/2403.19944).
