### ISSUE TITLE
Data normalization problem

### ISSUE THREAD

**Issue by WSM123123** [zhanggengchen/BRVE#4]
Hello, you have done a great job. Can you tell me how your LLRVE dataset is normalized.Due to the lack of mmedit.datasets component, I constructed the datasets component according to the official documentation of mmedit and the data read configuration you gave, but I don't know the details of how you normalized the data during the read phase, so I used the pre-trained model you gave to test very badly, how did you do it? Looking forward to your reply, thank you.

**Comment by zhanggengchen** [comment]
The code of mmedit.datasets has been updated.
